# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84bd169fe21e17baed038a37ac840ea298c6bf273b2f2256e260b78cee5bd74929d531be41cdd72034bd7040de90a257762a12152fa49f2219b5fb15d0f3744e

test:
  secret_key_base: 35413af9a326f1f85ce545748b3409650a289331601d057501aaeb029f00dbb0512b73fbb697d335ba1ac619b4757366ecf20a2e5a38e00a612f66a983c190b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
